### ISSUE TITLE
Local Development and merge with CICD

### ISSUE THREAD

**Issue by ee07dazn** [datarootsio/terraform-aws-ecs-airflow#8]
Hi Guys, 

Not really an issue but more of a question really - 

Thanks for creating this for the wider community. I am curious around how would a local development/testing and then merge with CICD work to integrate with this airflow. 

As in lets say i want to locallly test a dag or make changes to config and once my results look OK, i want to bring those changes in here with ease of development. 

On way I can think of is having my dockerfile and a config file, with my config file baked into it but then it will be a matter of which config takes precedence, the one in my dockerfile and mapped to  ${AIRFLOW_HOME}/airflow.cfg OR the one which is set through this repo. 

Any thoughts ?

**Comment by nicogelders** [comment]
Hey,

Very good question indeed. We do this by mimicking the airflow setup we have in aws with a docker-compose (an airflow container and an postrgres container) file and mount our dags to the airflow container.

As for the airflow.cfg, you can then just put the variables you want to override as env variables in the airflow container.

An example of a docker-compose file you could use:
```YAML
version: "3.7"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
  webserver:
    image: apache/airflow:1.10.12
    restart: always
    depends_on:
      - postgres
    environment:
      - EXECUTOR=Local
      - AIRFLOW__WEBSERVER__NAVBAR_COLOR=#e27d60
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432
    entrypoint: |
        bash -c "
            while ! nc -z 'postgres' '5432' >/dev/null 2>&1 </dev/null; do
                echo 'waiting for postgres'
                sleep 5
            done
            airflow initdb
            airflow scheduler & 
            airflow webserver
        "
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
```

Kr,
Nico.
